### ISSUE TITLE
em_timer_attr_init() fails with ODP v1.41.1 (linux-generic)

### ISSUE THREAD

**Issue by aCinal** [openeventmachine/em-odp#21]
Starting from ODP version v1.41.1, `em_timer_attr_init()` can fail due to the naive strategy of setting the resolution to `EM_ODP_TIMER_RESOL_DEF_NS` when calling `odp_timer_res_capability()` in `src/add-ons/event_timer/event_machine_timer.c`:

```c
/* strategy: first put default resolution, then validate based on that */
tmr_attr->resparam.res_ns = EM_ODP_TIMER_RESOL_DEF_NS;

...

odp_res_capa.res_ns = tmr_attr->resparam.res_ns;
err = odp_timer_res_capability(odp_clksrc, &odp_res_capa);
if (unlikely(err)) {
	INTERNAL_ERROR(EM_ERR_LIB_FAILED, EM_ESCOPE_TIMER_ATTR_INIT,
			"Timer res capability: ret %d, odp-clksrc:%d, res %lu",
			err, odp_clksrc, tmr_attr->resparam.res_ns);
	return;
}
```

The hardcoded resolution `EM_ODP_TIMER_RESOL_DEF_NS` may not be supported by ODP.

In commit `45ac01d900b42030eaaaed0499c457d1b16f0215` (`linux-gen: timer: check capability limits in odp_timer_res_capability()`) extra checks were added to `odp_timer_res_capability()`, which raise an error if the provided resolution (hardcoded to `EM_ODP_TIMER_RESOL_DEF_NS` in EM-ODP) exceeds the ODP capability, see `platform/linux-generic/odp_timer.c`:

```c
if (res_capa->res_ns && res_capa->res_ns < timer_global->highest_res_ns) {
	_ODP_DBG("Timeout resolution capability (res_ns) exceeded\n");
	return -1;
}
```
This makes `em_timer_attr_init()` unusable on platforms where the hardcoded resolution is too high, as the function now exits early due to this error and thus fails to set:

```c
tmr_attr->__internal_check = EM_CHECK_INIT_CALLED;
```

A simple fix would be to change
```c
odp_res_capa.res_ns = tmr_attr->resparam.res_ns;
```

to something like

```c
odp_res_capa.res_ns = tmr_attr->resparam.res_ns = odp_capa.highest_res_ns;
```

where `odp_capa` is already set by a prior call to `odp_timer_capability()`.

**Comment by kriwiks** [comment]
yes, can happen. In practise probably only with the posix-timer (which happens to be the default). Most users that we know use the inline timer or specific implementation (or specific setup values), that likely has no issue with 1ms. Inline (polling) timer can be selected in the odp runtime config file (pros and cons vs posix).

There were earlier some application developer wishes to have ~predictable default, one reason for this simple init. But as you pointed out it can fail so we can have a look how to improve it.

**Comment by cawallen** [comment]
ODP inline timer is recommended with EM - try it out:

odp/config/odp-linux-generic.conf:
```
timer: {
	# Use inline timer implementation
	#
	# By default, timer processing is done in background threads (thread per
	# timer pool). With inline implementation timers are processed by ODP
	# application threads instead. When using inline timers the application
	# has to call odp_schedule() or odp_queue_deq() regularly to actuate
	# timer processing.
	#
	# 0: Use POSIX timer and background threads to process timers
	# 1: Use inline timer implementation and application threads to process
	#    timers
	inline = 0 # Change this to 1
```

Further ODP options exist to limit the timer polling rate once enabled, see `inline_poll_interval` and `inline_poll_interval_ns`.

**Comment by aCinal** [comment]
Thank you. Inline timers do seem like an obvious choice for EM (and I missed it in the README). They both solve the problem of `em_timer_attr_init()` failing, and provide better accuracy.

Closing the issue :)
